# Master Dataset Creation

## Objective

The objective of this notebook is to create a standardized master dataset by integrating all selected training datasets into a common structure. Each dataset contributes different water quality parameters collected from different sources. During this stage, all datasets are aligned to a common schema, merged sequentially, validated after every merge, and intermediate versions are saved. The resulting master dataset will serve as the primary dataset for preprocessing and machine learning model development.

## Theory

A master dataset is created by combining multiple datasets into one standardized dataset. Since different datasets contain different water quality parameters and target variables, all datasets are first aligned to a common schema before merging. This approach ensures consistency in column names, simplifies future preprocessing, and provides a reliable dataset for machine learning. Missing values are intentionally preserved during this stage and will be handled during preprocessing.

In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
dataset_folder = "../../01_Datasets/Training Datasets"

dataset_files = sorted(
    [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
)

print("Training Datasets Found:\n")

for file in dataset_files:
    print(file)

Training Datasets Found:

Dataset01Filtered.csv
Dataset02Filtered.csv
Dataset03Filtered.csv
Dataset04Filtered.csv
Dataset09Filtered.csv
Dataset10Filtered.csv

In [4]:
datasets = {}

for file in dataset_files:

    path = os.path.join(dataset_folder, file)

    datasets[file] = pd.read_csv(path)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [27]:
MASTER_COLUMNS = [

    "pH",

    "Temperature",

    "Turbidity",

    "Total Dissolved Solids",

    "Conductivity",

    "Dissolved Oxygen",

    "Hardness",

    "Nitrate",

    "Chloride",

    "BOD",

    "Target",

    "WQI"

]

In [28]:
output_folder = "../../01_Datasets/Master Dataset"

os.makedirs(output_folder, exist_ok=True)

print("Output folder ready.")

Output folder ready.

In [29]:
master_dataset = pd.DataFrame()

version = 1

for file in dataset_files:

    print("="*60)
    print(f"Merging {file}")

    df = datasets[file].copy()

    # Add missing columns
    for column in MASTER_COLUMNS:

        if column not in df.columns:

            df[column] = np.nan

    # Arrange columns in standard order
    df = df[MASTER_COLUMNS]

    # Merge
    master_dataset = pd.concat(
        [master_dataset, df],
        ignore_index=True
    )

    print("Rows :", master_dataset.shape[0])
    print("Columns :", master_dataset.shape[1])

    # Save Version
    save_path = os.path.join(
        output_folder,
        f"Master_Dataset_v{version}.csv"
    )

    master_dataset.to_csv(save_path, index=False)

    print(f"Saved : Master_Dataset_v{version}.csv")

    version += 1

============================================================
Merging Dataset01Filtered.csv
Rows : 450
Columns : 12
Saved : Master_Dataset_v1.csv
============================================================
Merging Dataset02Filtered.csv
Rows : 1450
Columns : 12
Saved : Master_Dataset_v2.csv
============================================================
Merging Dataset03Filtered.csv
Rows : 3820
Columns : 12
Saved : Master_Dataset_v3.csv
============================================================
Merging Dataset04Filtered.csv
Rows : 1052395
Columns : 12
Saved : Master_Dataset_v4.csv
============================================================
Merging Dataset09Filtered.csv
Rows : 1098923
Columns : 12
Saved : Master_Dataset_v5.csv
============================================================
Merging Dataset10Filtered.csv
Rows : 1099218
Columns : 12
Saved : Master_Dataset_v6.csv

In [30]:
print(master_dataset.shape)

(1099218, 12)

In [36]:
df = pd.read_csv("../../01_Datasets/Master Dataset/Master_Dataset_v6.csv")

print(df.shape)

(1099218, 12)

C:\Users\Asus\AppData\Local\Temp\ipykernel_25184\390710062.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../01_Datasets/Master Dataset/Master_Dataset_v6.csv")

In [31]:
master_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1099218 entries, 0 to 1099217
Data columns (total 12 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pH                      1078893 non-null  float64
 1   Temperature             1069410 non-null  float64
 2   Turbidity               1041331 non-null  float64
 3   Total Dissolved Solids  1048727 non-null  float64
 4   Conductivity            1067045 non-null  float64
 5   Dissolved Oxygen        49793 non-null    float64
 6   Hardness                0 non-null        float64
 7   Nitrate                 1030175 non-null  float64
 8   Chloride                1017741 non-null  float64
 9   BOD                     1295 non-null     float64
 10  Target                  1050025 non-null  object
 11  WQI                     46823 non-null    float64
dtypes: float64(11), object(1)
memory usage: 100.6+ MB

In [32]:
master_dataset.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target,WQI
0,7.42,16.88,0.25,306.7,1486.1,7.41,NaN,NaN,NaN,NaN,Good,NaN
1,8.18,20.55,0.87,84.3,476.3,6.04,NaN,NaN,NaN,NaN,Moderate,NaN
2,5.58,26.25,1.99,676.7,479.9,6.71,NaN,NaN,NaN,NaN,Poor,NaN
3,7.93,30.15,0.06,852.9,713.5,3.24,NaN,NaN,NaN,NaN,Poor,NaN
4,8.37,12.32,3.37,161.2,1702.6,6.83,NaN,NaN,NaN,NaN,Poor,NaN

In [33]:
master_dataset.tail()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target,WQI
1099213,7.85,28.0,NaN,NaN,281.5,6.95,NaN,0.115,NaN,0.37,NaN,56.181191
1099214,7.95,28.0,NaN,NaN,274.0,6.90,NaN,0.150,NaN,0.60,NaN,54.711315
1099215,7.70,25.0,NaN,NaN,286.0,7.40,NaN,0.500,NaN,0.55,NaN,57.114775
1099216,7.90,28.0,NaN,NaN,1572.5,6.75,NaN,0.000,NaN,0.70,NaN,311.545107
1099217,7.95,28.5,NaN,NaN,9272.0,6.50,NaN,0.000,NaN,0.90,NaN,1834.549110

In [34]:
master_dataset.describe()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,WQI
count,1.078893e+06,1.069410e+06,1.041331e+06,1.048727e+06,1.067045e+06,49793.000000,0.0,1.030175e+06,1.017741e+06,1295.000000,46823.000000
mean,7.553462e+00,1.944768e+01,4.948359e-01,2.649560e+02,4.204101e+02,8.128839,NaN,6.077093e+00,1.818660e+02,5.041316,29.497322
std,1.008613e+00,1.121798e+01,9.350441e-01,1.546918e+02,1.916423e+02,1.142189,NaN,3.132758e+00,6.576657e+01,4.947525,18.314122
min,3.000000e-01,0.000000e+00,1.410000e-14,1.064299e-02,0.000000e+00,0.000000,NaN,0.000000e+00,2.941350e+01,0.000000,0.524595
25%,6.939589e+00,1.159265e+01,3.704042e-02,1.318441e+02,2.840863e+02,7.897651,NaN,3.951510e+00,1.374347e+02,2.199779,22.742093
50%,7.499027e+00,1.696412e+01,2.004124e-01,2.636467e+02,3.960364e+02,7.987861,NaN,5.563875e+00,1.747464e+02,4.439111,29.024594
75%,8.073356e+00,2.498987e+01,5.951770e-01,3.950733e+02,5.277007e+02,8.185179,NaN,7.584356e+00,2.156446e+02,7.238340,33.663885
max,1.397159e+01,2.430051e+02,1.996778e+01,1.197000e+03,9.272000e+03,19.918926,NaN,7.307293e+01,1.430549e+03,123.500000,1834.549110

In [35]:
print("Master Dataset Created Successfully.")

Master Dataset Created Successfully.

In [5]:
for file in dataset_files:
    print("=" * 60)
    print(file)

    if "Target" in datasets[file].columns:
        print(datasets[file]["Target"].value_counts(dropna=False))
    else:
        print("Target column not present.")

============================================================
Dataset01Filtered.csv
Target
Poor        358
Moderate     82
Good         10
Name: count, dtype: int64
============================================================
Dataset02Filtered.csv
Target
2    915
1     79
0      6
Name: count, dtype: int64
============================================================
Dataset03Filtered.csv
Target
NaN    2370
Name: count, dtype: int64
============================================================
Dataset04Filtered.csv
Target
0    807841
1    240734
Name: count, dtype: int64
============================================================
Dataset09Filtered.csv
Target column not present.
============================================================
Dataset10Filtered.csv
Target
NaN    295
Name: count, dtype: int64

# Conclusion

In this notebook, a standardized master dataset was successfully created by integrating all selected training datasets into a unified structure. Each dataset was automatically aligned to a predefined schema before merging, ensuring consistency across all records. Intermediate versions of the master dataset were generated after each merge to maintain traceability and simplify debugging. The final master dataset will serve as the primary dataset for preprocessing, exploratory data analysis, feature engineering, machine learning model training, and evaluation.